### PR TITLE
OTP-26 support

### PR DESCRIPTION
**Pull request by vheathen**
Change Erlang configuration fetch calls in the Makefile to eliminate race OTP-26 related conditions

More details in https://github.com/erlang/otp/issues/6916

### CODE REVIEW

**Comment by vheathen** [comment]
@cabol may I ask you to have a look at this PR?

**Comment by cabol** [comment]
Hey 👋 !! Thanks for the PR, at first glance LGTM, however, may I suggest you add the OTP 26 to the CI (since you're adding the 26, we can take advantage to also add the 25 since it is missing too)? Here: https://github.com/cabol/jchash/blob/master/.github/workflows/ci.yml#L15. THANKS!!

**Comment by vheathen** [comment]
@cabol sure, I've made changes. Thanks!

**Comment by cabol** [comment]
Sorry, I had to fix the CI because it was broken, and also took advantage to update the Makefile (via `rebar3`). I see it is working now fine with OTP 26 (included in the CI matrix), please try it out and let me know. Once you confirm it works, I can release a new version. Thanks!

**Comment by vheathen** [comment]
@cabol 
it looks it compiles now.
thanks a lot for your time and efforts!

**Pull request closed without merging**
