### PR TITLE
🐛 Fix compile under OTP 23

### LINKED ISSUE #3: Unable to build with OTP 23
On Ubuntu 20.04 trying to use OTP v23 with jchash i get the following:

```
$ mix deps.compile jchash
===> Compiling jchash
make: Entering directory '/project/deps/jchash/c_src'
cc -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/lib/erlang/erts-11.0.2/include/ -I /usr/lib/erlang/lib/erl_interface-4.0/include  -c -o /project/deps/jchash/c_src/jchash.o /project/deps/jchash/c_src/jchash.c
cc /project/deps/jchash/c_src/jchash.o -shared -L /usr/lib/erlang/lib/erl_interface-4.0/lib -lerl_interface -lei -o /project/deps/jchash/c_src/../priv/jchash.so
/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status
make: *** [Makefile:59: /project/deps/jchash/c_src/../priv/jchash.so] Error 1
make: Leaving directory '/project/deps/jchash/c_src'
===> Hook for compile failed!

$ dpkg -l|grep esl-erlang
ii  esl-erlang                                 1:23.0.2-1

```

Is the deprecation of erl_interface the reason, mentioned [here](http://erlang.org/doc/general_info/deprecations.html#legacy-parts-of-erl_interface)?

### PR DESCRIPTION
**Pull request by nikolaik**
I'm not sure what I am doing, but this seems to fix #3

### CODE REVIEW

**Comment by kenny-evitt** [comment]
@nikolaik I'm not sure what *you're* not sure about what you did but I'm glad you seem to have found a fix!

The changes *seem* pretty reasonable. You're saving the (major number) of the OTP release version in `ERL_OTP` and then, only for versions prior to 23.*x*, adding the option `-lerl_interface`.

Have you tested that the library still functions as expected with your change?

**Comment by Tyler-pierce** [comment]
After having the same error was able to use this branch to run under OTP 22 as well as OTP 23. I'm able to use :jchash.compute(erlang.phash2(), range). That's about all I'm able to confirm but so far so good for me. Thanks for posting this @nikolaik

**Comment by kenny-evitt** [comment]
@Tyler-pierce Thanks!

**Comment by nikolaik** [comment]
Thank you @Tyler-pierce !

> I'm not sure what you're not sure about what you did but I'm glad you seem to have found a fix!

@kenny-evitt I'm just very unfamiliar in the Erlang/Elixir C interface space, so unsure if this is the cleanest approach or linking with erlang libs is even necessary in OTP 22. Glad stuff seem to be working 😊

Have not gotten around to test this. Was hoping to get feedback from @cabol on the approach first

**Comment by cabol** [comment]
@nikolaik it looks ok to me, I'll merge it, thanks for your contribution 😉 👍 !!

**Comment by cabol** [comment]
BTW, just publish version bump `0.1.2`

**Comment by kenny-evitt** [comment]
@cabol Thanks! Would you be able to bump the version of this library in the dependencies of the Nebulex Redis adapter too sometime soon (and publish a new version)?

**Comment by cabol** [comment]
Sure thing!

**Comment by kenny-evitt** [comment]
@cabol I *think* it might be unnecessary as the dependency version is `"~> 0.1.1"` but I don't know how that works from another project that depends on the Redis adapter project directly.

**Pull request merged**
